import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useMemo, useRef, useState } from 'react'
import Webcam from 'react-webcam'
import styles from '../styles/Home.module.css'
import  Button  from './components/Button'
import {Cloudinary} from '@cloudinary/url-gen';
import Card from './components/Card'

const videoConstraints = {
  width: 720,
  height: 720,
  aspectRatio: 1
}

const FILTERS = ['al_dente', 'athena', 'audrey', 
                    'aurora', 'daguerre', 'eucalyptus',
                   'fes', 'frost', 'hairspray',
                    'hokusai', 'incognito', 'linen',
                   'peacock', 'primavera', 'quartz', 
                    'red_rock', 'refresh', 'sizzle', 'sonnet', 'ukulele', 'zorro'];


// Create your instance
const cloudinery = new Cloudinary({
  cloud: {
      cloudName: 'dx8lkxjh7'
  },
  url: {
      secure: true // force https, set to false to force http
  }
});


export default function Home() {
  const webcamRef = useRef<Webcam>(null);
  const [imageSrc, setImageSrc] = useState<string | undefined>();
  const initialData= {public_id: ''}
  const [uploadedData, setUploadedData] = useState(initialData);
  const [selectedFilter, setSelectedFilter] = useState('');

  const cloudImage = uploadedData?.public_id && cloudinery.image(uploadedData?.public_id);
  if (cloudImage){
    selectedFilter && 
    cloudImage.effect(`e_art:${selectedFilter}` as any)
  }
  const src  = (cloudImage && cloudImage.toURL() ) || imageSrc;
  
  const handleClick = () => {
    const image = webcamRef?.current?.getScreenshot();
    image && setImageSrc(image)
  }
  const handleReset = () => {
    setUploadedData(initialData)
    setImageSrc(undefined)
  }
  const handleDownload = async () => {
    const url = cloudImage && cloudImage.toURL();
    const image = await fetch(url)
    const imageBlog = await image.blob()
    const imageURL = URL.createObjectURL(imageBlog)

    const link = document.createElement('a')
    link.href = imageURL
    link.download = selectedFilter? `image_${selectedFilter}.jpg` : 'image.jpg';
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  const sampleCall = async () => {
    const res = await fetch('/api/cloudinary/upload', {
      method:'POST',
      body: JSON.stringify({
        image: imageSrc
      })
    }).then(r=> r.json());
    setUploadedData(res);
    console.log('response', res);
  }

  useEffect(()=>{
    if(!imageSrc) return;
    sampleCall();
  },[imageSrc])
  return (
    <div className={styles.container}>
      <Head>
        <title>Pro-Photoshop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      

      <main className={styles.main}>
        <div className={styles.topbar}>
          <p>Pro-Photoshop</p>
        </div>
        <div className={styles.grid}>
        {src ?
          (
            <img src={src} alt="display"/>
          ):
          (
           <Webcam ref={webcamRef} mirrored videoConstraints={videoConstraints} width={300}/> 
          )}
        <div className={styles.action_container}>
          <Button
          text={'Capture'}
          className={styles.capture_btn}
          onClick={handleClick}/>
          <Button
          text={'Reset'} 
          className={styles.reset_btn}
          onClick={handleReset}/>
          <Button
          text={'Download'} 
          className={styles.download_btn}
          onClick={handleDownload}/>
        </div>
        </div>
        <div className={styles.filter_text}>Filters:</div>
        <div className={styles.filter_container}>
        {FILTERS.map((item, index)=>(
          <Card key={`filter-${index}`} onClick={() => setSelectedFilter(item)} >
            <img width={100} height={100} src={cloudinery.image('Mountain_xxq3uv').effect(`e_art:${item}` as any).toURL()}/>
            <p>{item}</p>
          </Card>
        ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
